django/helloworld/books/urls.py
from django.urls import path

from .models import Publisher
from .views import index_view, publisher_view


urlpatterns = [
    path('', index_view),
]

for pub in Publisher.objects.all():
    urlpatterns += [
        path(pub.name_en, publisher_view, kwargs={'pub_obj': pub})
    ]

django/helloworld/books/models.py
from django.db import models
from django.db.models import base
from django.db.models import fields
from django.db.models.fields import related

from transliterate import translit


class Author(base.Model):
    first_name = fields.CharField(max_length=30)
    last_name = fields.CharField(max_length=50)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

class Book(base.Model):
    title = fields.CharField(max_length=50)
    author = related.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.title}'

class Publisher(base.Model):
    name = fields.CharField(max_length=50)
    authors = related.ManyToManyField(Author)
    books = related.ManyToManyField(Book)

    @property
    def name_en(self):
        return translit(str(self.name).lower(), reversed=True)

    def __str__(self):
        return f'{self.name}'


# после каждого изменения модели
# > py manage.py makemigrations books

# (опционально) компиляция SQL кода в файл
# > py manage.py sqlmigrate %имя_приложения% %номер_миграции% > %имя_приложения%\migrations\%номер_миграции%.sql

# применить миграции
# > py manage.py migrate --database=books_db

django/helloworld/books/views.py
from django.shortcuts import render

from random import choice

from .models import Book, Publisher


tips = (
    'Не печалься о том, что выходит за границы контроля. Не можешь изменить — нечего убиваться.',
    'То, что видишь перед собой, зависит от того, как именно на это смотришь.',
    'Обращай внимание только на советы, которые дают мудрые люди, заслужившие твое уважение.',
    'Верьте в тех, кто встретится на жизненном пути. Некоторые разочаруют, но будут и те, благодаря которым разочарование улетучится.',
    'Не ожидай, что кому-то захочется подарить тебе радость. Научись радовать себя самостоятельно, даже в одиночестве.',
    'То, от чего твое сердце счастливо трепещет, не обязательно сделает счастливым кого-то другого.',
    'В своих проблемах не ищи виноватых. Посмотри в зеркало.',
    'Уже не важно, что было раньше. Ещё не имеет значения, что будет дальше. Важен текущий момент, который нельзя упустить.'
)


def index_view(request):
    return render(
        request,
        'books/base.html',
        {
            'head_title': 'Главная',
            'body_title': 'Список книг',
            # 'align': 'center',
            'text': f"Совет дня:\n{choice(tips)}",
            'books': Book.objects.order_by('author', 'title'),
        }
    )


def publisher_view(request, pub_obj: Publisher):
    return render(
        request,
        'books/pubs.html',
        {
            'head_title': pub_obj.name,
            'body_title': f'Авторы и книги издательства {pub_obj.name}',
            'authors': pub_obj.authors.order_by('last_name')
        }
    )

django/helloworld/books/templates/books/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ head_title }}</title>
</head>
<body>
    <h2>{{ body_title }}</h2>
    <div align="{{ align|default:'right' }}">
        <p>{{ text }}</p>
    </div>
    <table cellpadding="10">
        {% for book in books %}
            <tr>
                <td>{{ book.author }}</td>
                <td>{{ book }}</td>
                <td><a href="/books/{{ book.publisher_set.get.name_en }}">{{ book.publisher_set.get }}</a></td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

django/helloworld/books/templates/books/pubs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ head_title }}</title>
</head>
<body>
    <h2>{{ body_title }}</h2>
    <div align="center">
      <table cellpadding="10">
        {% for author in authors %}
          {% for book in author.book_set.all %}
            <tr>
              <td>{{ author }}</td>
              <td>{{ book }}</td>
            </tr>
          {% endfor %}
        {% endfor %}
      </table>
    </div>
</body>
</html>