django/academy/core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('faculties.urls')),
    path('auth/', include('users.urls')),
    path('admin/', admin.site.urls),
]

django/academy/faculties/urls.py
from django.urls import path, re_path

from .models import Faculty
from .views_fb import university_main_view, faculties_list_view, faculty_view
from .views_cb import UniversityMainView, FacultyView


FUNCTIONS_OR_CLASS = 0

if FUNCTIONS_OR_CLASS:
    university_main_view = UniversityMainView.as_view()
    faculty_view = FacultyView.as_view()


urlpatterns = [
    path('', university_main_view, name='main'),
    path('faculties/', faculties_list_view, name='faculties'),
]

for faculty in Faculty.objects.all():
    urlpatterns += [
        re_path(
            f'{faculty.short_en}{faculty.id}/',
            faculty_view,
            kwargs={'pk': faculty.id}
        ),
    ]

django/academy/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import UserLoginView, UserLogoutView, UserRegistrationView

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', UserRegistrationView.as_view(), name='register'),
]

django/academy/faculties/models.py
from django.db import models


class Faculty(models.Model):
    name = models.CharField(db_column='Name', unique=True, max_length=100)

    class Meta:
        managed = False
        db_table = 'faculties'

    @property
    def short_en(self):
        return ''.join((
            word[0]
            for word in str(self.name).lower().split()
            if len(word) > 2
        ))


class Department(models.Model):
    building = models.PositiveSmallIntegerField(db_column='Building')
    financing = models.DecimalField(db_column='Financing', max_digits=10, decimal_places=2)
    name = models.CharField(db_column='Name', unique=True, max_length=100)
    faculty = models.ForeignKey(Faculty, models.CASCADE, db_column='FacultyId')

    class Meta:
        managed = False
        db_table = 'departments'

    @property
    def short_en(self):
        return ''.join((
            word[0]
            for word in str(self.name).lower().split()
            if len(word) > 2
        ))


class Student(models.Model):
    name = models.CharField(db_column='Name', max_length=30)
    surname = models.CharField(db_column='Surname', max_length=30)
    rating = models.PositiveSmallIntegerField(db_column='Rating')

    class Meta:
        managed = False
        db_table = 'students'


class Curator(models.Model):
    name = models.CharField(db_column='Name', max_length=30)
    surname = models.CharField(db_column='Surname', max_length=30)

    class Meta:
        managed = False
        db_table = 'curators'


class Subject(models.Model):
    name = models.CharField(db_column='Name', unique=True, max_length=100)

    class Meta:
        managed = False
        db_table = 'subjects'


class Teacher(models.Model):
    name = models.CharField(db_column='Name', max_length=30)
    surname = models.CharField(db_column='Surname', max_length=30)
    salary = models.DecimalField(db_column='Salary', max_digits=8, decimal_places=2)
    isprofessor = models.BooleanField(db_column='IsProfessor')
    subjects = models.ManyToManyField(Subject, through='Lecture')

    class Meta:
        managed = False
        db_table = 'teachers'


class Lecture(models.Model):
    date = models.DateField(db_column='Date')
    subject = models.ForeignKey(Subject, models.CASCADE, db_column='SubjectId')
    teacher = models.ForeignKey(Teacher, models.CASCADE, db_column='TeacherId')

    class Meta:
        managed = False
        db_table = 'lectures'


class Group(models.Model):
    name = models.CharField(db_column='Name', unique=True, max_length=10)
    year = models.PositiveIntegerField(db_column='Year')
    department = models.ForeignKey(Department, models.CASCADE, db_column='DepartmentId')
    students = models.ManyToManyField(Student, through='GroupsStudents')
    curators = models.ManyToManyField(Curator, through='GroupsCurators')
    lectures = models.ManyToManyField(Lecture, through='GroupsLectures')

    class Meta:
        managed = False
        db_table = 'groups'


class GroupsStudents(models.Model):
    student = models.ForeignKey(Student, models.CASCADE, db_column='StudentId')
    group = models.ForeignKey(Group, models.CASCADE, db_column='GroupId')

    class Meta:
        managed = False
        db_table = 'groupsstudents'


class GroupsCurators(models.Model):
    curator = models.ForeignKey(Curator, models.CASCADE, db_column='CuratorId')
    group = models.ForeignKey(Group, models.CASCADE, db_column='GroupId')

    class Meta:
        managed = False
        db_table = 'groupscurators'


class GroupsLectures(models.Model):
    lecture = models.ForeignKey(Lecture, models.CASCADE, db_column='LectureId')
    group = models.ForeignKey(Group, models.CASCADE, db_column='GroupId')

    class Meta:
        managed = False
        db_table = 'groupslectures'

django/academy/users/models.py
from django.db import models

# Create your models here.

django/academy/faculties/forms.py
from django import forms
from django.forms import fields
from django.forms import widgets


class DepartmentAddForm(forms.Form):
    name = fields.CharField(
        label='Name:',
        max_length=100,
        widget=widgets.TextInput(
            attrs={
                'placeholder': ''
            }
        ),
    )
    financing = fields.DecimalField(
        label='Financing:',
        min_value=0,
        max_digits=10,
        decimal_places=2,
        widget=widgets.NumberInput(
            attrs={
                'placeholder': ''
            }
        ),
    )
    building = fields.IntegerField(
        label='Building:',
        min_value=1,
        max_value=5,
        widget=widgets.NumberInput(
            attrs={
                'placeholder': ''
            }
        ),
    )


class DepartmentDelForm(forms.Form):
    name = fields.CharField(
        label='Name:',
        max_length=100,
        widget=widgets.TextInput(
            attrs={
                'placeholder': ''
            }
        )
    )

django/academy/faculties/views.py
from django.views.generic import ListView, DetailView

from .models import Faculty


class UniversityMainView(ListView):
    model = Faculty
    template_name = 'faculties/main.html'


class FacultyView(DetailView):
    model = Faculty
    template_name = 'faculties/faculty.html'

django/academy/users/views.py
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import redirect
from django.views.generic import FormView


# Create your views here.


class UserLoginView(LoginView):
    template_name = 'users/login.html'


class UserLogoutView(LogoutView):
    def post(self, request, *args, **kwargs):
        logout(request)
        return redirect(self.next_page)


class UserRegistrationView(FormView):
    form_class = UserCreationForm
    template_name = 'users/register.html'
    success_url = '/auth/login/'

    def form_valid(self, form: UserCreationForm):
        form.save()
        return redirect(self.get_success_url())

django/academy/faculties/templates/bs_faculties/faculties_list.html
{% extends base_template|default:"bs_faculties/main.html" %}


{% block first_part %}
    <h2 class="display-2">Faculties list</h2>
    <div>
        <ul class="list-style">
        {% for faculty in object_list %}
            <li><a href="/{{ faculty.short_en }}{{ faculty.id }}">{{ faculty.name }}</a></li>
        {% endfor %}
        </ul>
    </div>
{% endblock first_part %}

django/academy/faculties/templates/bs_faculties/faculty.html
{% extends base_template|default:"bs_base.html" %}

{% load bootstrap5 %}


{% block content %}
    <div class="row justify-content-center">
        <h2 class="display-2">{{ object.name }}</h2>
    </div>
    <div class="row justify-content-start">
        <h3 class="display-3">Departments list</h3>
        <div>
            <ul class="list-style">
            {% for department in object.department_set.all %}
                <li>{{ department.name }}</li>
            {% endfor %}
            </ul>
        </div>
    </div>
    <div class="text-success">
        <hr>
    </div>
    <h4 class="display-4">Add department</h4>
    <div class="row justify-content-start">
        <form action="/{{ object.short_en }}{{ object.id }}/"
              method="post"
              name="add">
            {% csrf_token %}

            {% bootstrap_form form_add %}

            <input class="btn btn-primary"
                   type="submit"
                   name="SubmitAdd"
                   value="Save">
        </form>
    </div>
    <div class="text-success">
        <hr>
    </div>
    <h4 class="display-4">Delete department</h4>
    <div class="row justify-content-start">
        <form action="/{{ object.short_en }}{{ object.id }}/"
              method="post"
              name="del">
            {% csrf_token %}
            {% bootstrap_form form_del %}
            <input class="btn btn-primary"
                   type="submit"
                   name="SubmitDel"
                   value="Delete">
        </form>
    </div>
{% endblock content %}


{% block footer %}
{% endblock footer %}

django/academy/faculties/templates/bs_faculties/main.html
{% extends base_template|default:"bs_base.html" %}


{% block content %}

    <div class="row justify-content-center">
        <h1 class="display-1">Massachusetts Institute of Technology</h1>
    </div>

    <div class="row justify-content-start">
        {% block first_part %}
        {% endblock first_part %}
    </div>

{% endblock content %}

django/academy/faculties/templates/faculties/faculties_list.html
{% extends base_template|default:"faculties/main.html" %}


{% block first_part %}
    <h2>Faculties list</h2>
    <div class="list-simple">
        <ul>
        {% for faculty in object_list %}
            <li><a href="/{{ faculty.short_en }}{{ faculty.id }}">{{ faculty.name }}</a></li>
        {% endfor %}
        </ul>
    </div>
{% endblock first_part %}

django/academy/faculties/templates/faculties/faculty.html
{% extends base_template|default:"base.html" %}


{% block content %}
    <div align="center">
        <h2>{{ object.name }}</h2>
    </div>
    <div>
        <h3>Departments list</h3>
        <div class="list-simple">
            <ul>
            {% for department in object.department_set.all %}
                <li>{{ department.name }}</li>
            {% endfor %}
            </ul>
        </div>
    </div>
    <hr>
    <h4>Add department</h4>
    <div>
        <form action="/{{ object.short_en }}{{ object.id }}/" method="post" name="add">
            {% csrf_token %}
            <div>
                {{ form_add.as_p }}
            </div>
            <div>
                <input type="submit" name="SubmitAdd">
            </div>
        </form>
    </div>
    <hr>
    <h4>Delete department</h4>
    <div>
        <form action="/{{ object.short_en }}{{ object.id }}/" method="post">
            {% csrf_token %}
            <div>
                {{ form_del.as_p }}
            </div>
            <div>
                <input type="submit" name="SubmitDel">
            </div>
        </form>
    </div>
{% endblock content %}


{% block footer %}
{% endblock footer %}

django/academy/faculties/templates/faculties/main.html
{% extends base_template|default:"base.html" %}


{% block content %}
    <div align="center">
        <h1>Massachusetts Institute of Technology</h1>
    </div>

    <div>
        {% block first_part %}
        {% endblock first_part %}
    </div>

{% endblock content %}

django/academy/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static base_style|default:'styles/base.css' %}">
    {% for style in styles|default:'' %}
        <link rel="stylesheet" href="{% static style %}">
    {% endfor %}
    <title>{{ page_title|default:"MIT" }}</title>
</head>
<body>
<!-- header -->
    <div class="header-simple">
        {% block header %}
            {% include "includes/navbar.html" %}
        {% endblock header %}
    </div>
<!-- /header -->

<!-- content -->
    <div class="content-simple">
        {% block content %}
        {% endblock content %}
    </div>
<!-- /content -->

<!-- footer -->
    <div class="footer-simple">
        {% block footer %}
            <hr>
            <div align="right">
                <p>Developed for studying with Django 4.1</p>
            </div>
            <img src="{% static 'images/bottom_cr.png' %}"
                 alt=""
                 width="100%">
        {% endblock footer %}
    </div>
<!-- /footer -->
</body>
</html>

django/academy/templates/bs_base.html
{% extends 'bootstrap5/bootstrap5.html' %}

{% load static %}


{% block bootstrap5_title %}
    {{ page_title|default:"MIT" }}
{% endblock bootstrap5_title %}


{% block bootstrap5_extra_head %}
{% endblock bootstrap5_extra_head %}


{% block bootstrap5_before_content %}
<!-- header -->
    <div class="container-fluid">
        {% block header %}
            {% include "includes/navbar.html" %}
        {% endblock header %}
    </div>
<!-- /header -->
{% endblock bootstrap5_before_content %}


{% block bootstrap5_content %}
<!-- content -->
    <div class="container-fluid">
        {% block content %}
        {% endblock content %}
    </div>
<!-- /content -->
{% endblock bootstrap5_content %}


{% block bootstrap5_after_content %}
<!-- footer -->
    <div class="container">
        {% block footer %}
            <hr>
            <div class="row justify-content-end">
                <div class="col">
                    Developed for studying with Django 4.1
                </div>
            </div>
            <div class="row justify-content-center">
                <img src="{% static 'images/bottom_cr.png' %}"
                     alt=""
                     width="100%">
            </div>
        {% endblock footer %}
    </div>
<!-- /footer -->
{% endblock bootstrap5_after_content %}


{% block bootstrap5_extra_script %}
{% endblock bootstrap5_extra_script %}

django/academy/templates/includes/navbar.html
<div>
    <table cellpadding="20">
        <tr>
            <td>
                {% if user.is_authenticated %}
                    {{ user.username }}, <a href="{% url 'logout' %}?next={{ current_url }}">logout</a>
                {% else %}
                    <a href="/auth/login/">Login</a>
                {% endif %}
            </td>
            <td width="50px"></td>
            <td><a href="/">Main</a></td>
            <td><a href="/faculties/">Faculties</a></td>
            <td><a>About</a></td>
            <td><a>Contact form</a></td>
        </tr>
    </table>
    <hr>
</div>

django/academy/users/templates/users/login.html
{% extends base_template|default:"bs_base.html" %}

{% load static %}


{% block bootstrap5_title %}
    Login
{% endblock bootstrap5_title %}


{% block bootstrap5_before_content %}
<!-- header -->
<!-- /header -->
{% endblock bootstrap5_before_content %}


{% block bootstrap5_content %}
<!-- content -->
    <div class="container-fluid">
        <form action="{% url 'login' %}"
              method="post">
            {% csrf_token %}
            <div>
                {{ form }}
            </div>
            <div>
                <input type="submit"
                       class="btn btn-primary"
                       value="Login">
            </div>
            <input type="hidden" name="next" value="{{ next }}">
        </form>
    </div>
    <div>
        <a href="{% url 'register' %}">Register</a>
    </div>
<!-- /content -->
{% endblock bootstrap5_content %}


{% block bootstrap5_after_content %}
<!-- footer -->
    <div class="container">
        {% block footer %}
            <hr>
            <div class="row justify-content-end">
                <div class="col">
                    Developed for studying with Django 4.1
                </div>
            </div>
            <div class="row justify-content-center">
                <img src="{% static 'images/bottom_cr.png' %}"
                     alt=""
                     width="100%">
            </div>
        {% endblock footer %}
    </div>
<!-- /footer -->
{% endblock bootstrap5_after_content %}

django/academy/users/templates/users/logout.html
{% extends base_template|default:"bs_base.html" %}

{% load static %}


{% block bootstrap5_title %}
    Logout
{% endblock bootstrap5_title %}


{% block bootstrap5_before_content %}
<!-- header -->
<!-- /header -->
{% endblock bootstrap5_before_content %}


{% block bootstrap5_content %}
<!-- content -->
    <div class="container-fluid">
        <p>Successfully logged out.</p>
    </div>
<!-- /content -->
{% endblock bootstrap5_content %}


{% block bootstrap5_after_content %}
<!-- footer -->
    <div class="container">
        {% block footer %}
            <hr>
            <div class="row justify-content-end">
                <div class="col">
                    Developed for studying with Django 4.1
                </div>
            </div>
            <div class="row justify-content-center">
                <img src="{% static 'images/bottom_cr.png' %}"
                     alt=""
                     width="100%">
            </div>
        {% endblock footer %}
    </div>
<!-- /footer -->
{% endblock bootstrap5_after_content %}

django/academy/users/templates/users/register.html
{% extends base_template|default:"bs_base.html" %}

{% load static %}


{% block bootstrap5_title %}
    New user
{% endblock bootstrap5_title %}


{% block bootstrap5_before_content %}
<!-- header -->
<!-- /header -->
{% endblock bootstrap5_before_content %}


{% block bootstrap5_content %}
<!-- content -->
    <div class="container-fluid">
        <form action="{% url 'register' %}"
              method="post">
            {% csrf_token %}
            <div>
                {{ form }}
            </div>
            <div>
                <input type="submit"
                       class="btn btn-success"
                       value="Register">
            </div>
            <input type="hidden" name="next" value="{{ next }}">
        </form>
    </div>
<!-- /content -->
{% endblock bootstrap5_content %}


{% block bootstrap5_after_content %}
<!-- footer -->
    <div class="container">
        {% block footer %}
            <hr>
            <div class="row justify-content-end">
                <div class="col">
                    Developed for studying with Django 4.1
                </div>
            </div>
            <div class="row justify-content-center">
                <img src="{% static 'images/bottom_cr.png' %}"
                     alt=""
                     width="100%">
            </div>
        {% endblock footer %}
    </div>
<!-- /footer -->
{% endblock bootstrap5_after_content %}